--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------
  DROP TABLE "LMSAPPUSER"."USERS" ;
  CREATE TABLE "LMSAPPUSER"."USERS" 
   ("USER_ID" VARCHAR2(40) NOT NULL,
	"NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"EMAILID" VARCHAR2(50 BYTE) , 
	"CONTACT_NO" NUMBER, 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"PREFLANG" VARCHAR2(50 BYTE), 
	"PREFLEARNINGMODE" VARCHAR2(50 BYTE), 
	"ISHEARINGIMPAIRED" VARCHAR2(1 BYTE), 
	"ISVISUALLYIMPAIRED" VARCHAR2(1 BYTE),
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
   )  
  TABLESPACE "DATA" ;
  
--REM INSERTING into LMSAPPUSER.USERS
SET DEFINE OFF;
Insert into LMSAPPUSER.USERS (USER_ID,NAME,LAST_NAME,EMAILID,CONTACT_NO,ADDRESS,PREFLANG,PREFLEARNINGMODE,ISHEARINGIMPAIRED,ISVISUALLYIMPAIRED) values (SYS_GUID(),'Navin','Sharma','navin.sharma@gmail.com',9769032843,'Mehsana','Hindi','Offline','Y','N');
Insert into LMSAPPUSER.USERS (USER_ID,NAME,LAST_NAME,EMAILID,CONTACT_NO,ADDRESS,PREFLANG,PREFLEARNINGMODE,ISHEARINGIMPAIRED,ISVISUALLYIMPAIRED) values (SYS_GUID(),'Manish','Dariyani','mddaryani@gmail.com',9769032844,'Slough','English','Online','N','N');
Insert into LMSAPPUSER.USERS (USER_ID,NAME,LAST_NAME,EMAILID,CONTACT_NO,ADDRESS,PREFLANG,PREFLEARNINGMODE,ISHEARINGIMPAIRED,ISVISUALLYIMPAIRED) values (SYS_GUID(),'Rajul','Dash','dashrajul89@gmail.com',9728232845,'Hayes','English','Online','Y','Y');
Insert into LMSAPPUSER.USERS (USER_ID,NAME,LAST_NAME,EMAILID,CONTACT_NO,ADDRESS,PREFLANG,PREFLEARNINGMODE,ISHEARINGIMPAIRED,ISVISUALLYIMPAIRED) values (SYS_GUID(),'Faneh','Khan','fanehkhan@gmail.com',1425378377,'Mumbai','English','Offline','N','Y');
Insert into LMSAPPUSER.USERS (USER_ID,NAME,LAST_NAME,EMAILID,CONTACT_NO,ADDRESS,PREFLANG,PREFLEARNINGMODE,ISHEARINGIMPAIRED,ISVISUALLYIMPAIRED) values (SYS_GUID(),'Julian','Colin','colin.julian@gmail.com',9187032847,'Ahmedabad','Hindi','Offline','Y','N');
Insert into LMSAPPUSER.USERS (USER_ID,NAME,LAST_NAME,EMAILID,CONTACT_NO,ADDRESS,PREFLANG,PREFLEARNINGMODE,ISHEARINGIMPAIRED,ISVISUALLYIMPAIRED) values (SYS_GUID(),'Anderson','Miriah','mranderson@gmail.com',1279032848,'Washington','English','Online','N','N');
Insert into LMSAPPUSER.USERS (USER_ID,NAME,LAST_NAME,EMAILID,CONTACT_NO,ADDRESS,PREFLANG,PREFLEARNINGMODE,ISHEARINGIMPAIRED,ISVISUALLYIMPAIRED) values (SYS_GUID(),'Jayesh','Milan','jayesh.milan@gmail.com',9769032849,'California','English','Offline','N','N');
